export const instrumentTypeMap = {
  "Common Stock": "Ação ordinária",
  "Preference": "Ação preferencial",
  "Unit": "Unit (pacote de ações)",
  "ETP": "Produto negociado em bolsa",
  "Open-End Fund": "Fundo aberto",
  "Closed-End Fund": "Fundo fechado",
  "REIT": "Fundo imobiliário",
  "ETF": "Fundos de Investimento Negociados",
  "CRYPTO": "Criptomoedas",
  "MLP": "Parceria limitada negociada",
  "Tracking Stk": "Ação vinculada a uma divisão da empresa",
  "Stapled Security": "Título composto inseparável",
  "Equity WRT": "Warrant de ações",
  "Right": "Direito de subscrição",
  "Receipt": "Recibo representativo de ativo",
  "ADR": "Recibo de ações estrangeiras nos EUA",
  "GDR": "Recibo global de ações",
  "BDR": "Ações Estrangeiras",
  "FII": "Fundo de Investimento Imobiliário",
  "Canadian DR": "Recibo depositário canadense",
  "Dutch Cert": "Certificado holandês de ações",
  "Foreign Sh.": "Ação estrangeira",
  "NVDR": "Recibo depositário sem direito a voto",
  "Savings Share": "Ação de poupança",
  "Royalty Trst": "Fundo de royalties",
  "Ltd Part": "Parceria limitada",
  "PUBLIC": "Empresa pública",
  "PRIVATE": "Empresa privada",
  "NY Reg Shrs": "Ações registradas em Nova York",
  "CDI": "Certificado de depósito",
  "SDR": "Direitos especiais de saque",
  "Misc.": "Outros instrumentos"
}

export const micNameMap = {
  OOTC: "Mercado de Balcão (OTC)",
  ARCX: "NYSE Arca",
  XNYS: "New York Stock Exchange (NYSE)",
  BATS: "Cboe BATS Exchange",
  XNAS: "Nasdaq Stock Market",
  XASE: "NYSE American",
  IEXG: "Investors Exchange (IEX)",
  BVMF: "B3 - São Paulo"
}
